name: 'Hugo Deploys for GitHub Pages'
description: 'Builds and deploys Hugo-generated websites to GitHub Pages'

branding:
  icon: 'home'
  color: 'green'

inputs:
  hugo_version:
    # See https://github.com/gohugoio/hugo/releases
    description: 'Version of Hugo to use'
    required: true
    default: '0.59.1'
  build_folder:
    description: 'Folder in which hugo generates the website'
    required: true
    default: 'public'
  build_branch:
    description: 'Branch in which the website is published'
    required: true
    default: 'master'
  github_token:
    description: 'Token to use to deploy the new version'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.hugo_version }}
    - ${{ inputs.build_folder }}
    - ${{ inputs.github_token }}
    - ${{ inputs.build_branch }}
