name: CI
on: [pull_request]

jobs:
  shellcheck:
    name: shellcheck
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          depth: 1

      - uses: reviewdog/action-shellcheck@v1
        with:
          github_token: ${{ github.token }}
          reporter: github-pr-review

  dockerfile:
    name: hadolint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          depth: 1

      - uses: burdzwastaken/hadolint-action@master
        env:
          GITHUB_TOKEN: ${{ github.token }}
          HADOLINT_ACTION_DOCKERFILE_FOLDER: .
